import { webkit } from "playwright";
import { LONG_STROKE_BODY } from "./acrylic-longstroke.page.js";
const browser = await webkit.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
const errors = [];
page.on("pageerror", (e) => errors.push(String(e)));
page.on("console", (m) => { if (m.type() === "error") errors.push(m.text()); });
await page.goto("http://127.0.0.1:5183/?perfDebug=1&gpuBackend=webgl2&stallThresholdMs=0", { waitUntil: "networkidle" });
await page.locator("button").filter({ hasText: /^Acrylic$/ }).click();
const canvas = page.locator("canvas[data-headless-paint-main]");
await canvas.waitFor();
const body = LONG_STROKE_BODY.replace("__BATCHES__", "20").replace("__SAMPLES__", "8");
const fn = new Function("element", body);
await canvas.evaluate(fn);
await page.waitForTimeout(200);
await page.evaluate(() => { globalThis.__hpBrushPerf?.reset(); const p = globalThis.__hpBrushPerf; globalThis.__evt = []; const orig = p.recordEvent.bind(p); p.recordEvent = (name, d) => { globalThis.__evt.push(name + (d && d.reason ? ":" + d.reason : "")); return orig(name, d); }; });
await page.getByLabel("Undo", { exact: true }).first().click();
await page.waitForTimeout(300);
await canvas.evaluate(fn);
await page.waitForTimeout(200);
const snap = await page.evaluate(() => JSON.stringify(globalThis.__hpBrushPerf?.snapshot()));
const st=JSON.parse(snap).stalls; const names=st.flatMap(x=>x.events.map(e=>e.name+(e.reason?":"+e.reason:""))); console.log("events:", names.filter(n=>/warmUp|residency|Upload/.test(n)));
console.log("spied events:", JSON.stringify(await page.evaluate(() => globalThis.__evt)));
console.log("stored recentEvents:", JSON.stringify((await page.evaluate(() => globalThis.__hpBrushPerf.snapshot().recentEvents)).map(e => e.name + (e.reason ? ":" + e.reason : ""))));
console.log("residencyHit samples after undo+stroke:", JSON.parse(snap).samples.gpuResidencyHit, "upload count:", JSON.parse(snap).stages.gpuUpload);
const s = JSON.parse(snap);
console.log("snapshot keys", Object.keys(s));
const text = snap;
console.log("warmUp events:", (text.match(/"warmUp"/g) || []).length, "invalidated:", (text.match(/residencyInvalidated/g) || []).length, "gpuUpload:", (text.match(/"gpuUpload"/g) || []).length);
console.log("engine backend text:", await page.locator("body").innerText().then(t => (t.match(/Engine[^\n]*/) || [""])[0]));
console.log("errors", errors.slice(0, 3));
await browser.close();
