export type {
  BackgroundSettings,
  BrushConfig,
  BristleBranchRenderState,
  BristleBrushConfig,
  BristleDynamics,
  BristlePressureDynamics,
  BristleSurfaceGrain,
  BristleSweepPointState,
  BrushBranchRenderState,
  BrushDynamics,
  BrushMixing,
  BrushMixingState,
  BrushRenderState,
  BrushTipConfig,
  CircleTipConfig,
  Color,
  CompiledExpand,
  ContentBounds,
  DensityProfileCurve,
  ExpandConfig,
  ExpandLevel,
  ExpandMode,
  ImageTipConfig,
  Layer,
  LayerMeta,
  LayerTransformPreview,
  PendingOverlay,
  ParametricCurve,
  Point as EnginePoint,
  PressureCurve,
  PressureDynamics,
  RoundPenBrushConfig,
  SprayBrushConfig,
  SprayDynamics,
  SprayPressureDynamics,
  SpraySizeJitterMode,
  StampBrushConfig,
  StrokePoint,
  StrokeStyle,
} from "@headless-paint/engine";

export {
  AIRBRUSH,
  BRUSH_MIXING_MAX_CHECKPOINT_DISTANCE_PX,
  BRUSH_MIXING_MAX_FIELD_DIMENSION,
  BRUSH_MIXING_MIN_FIELD_DIMENSION,
  DEFAULT_BACKGROUND_COLOR,
  DEFAULT_BRISTLE_DYNAMICS,
  DEFAULT_BRISTLE_PRESSURE_DYNAMICS,
  DEFAULT_BRUSH_DYNAMICS,
  DEFAULT_BRUSH_MIXING,
  DEFAULT_PRESSURE_CURVE,
  DEFAULT_PRESSURE_DYNAMICS,
  DEFAULT_RADIAL_DISTRIBUTION,
  DEFAULT_SPRAY_DYNAMICS,
  DEFAULT_SPRAY_PRESSURE_DYNAMICS,
  MARKER,
  PENCIL,
  ROUND_PEN,
  ROUGH_BRISTLE,
  SPRAY_AIRBRUSH,
  SPRAY_MAX_PARTICLES_PER_EMISSION,
} from "@headless-paint/engine";

export {
  hashSeed,
  mulberry32,
  renderBrushStroke,
  timeSpacingMsFromRate,
  walkEmissions,
  type DistanceSpacingAt,
  type EmissionPoint,
} from "@headless-paint/engine";
export {
  createBrushTipRegistry,
  generateBrushTip,
  type BrushTipRegistry,
} from "@headless-paint/engine";
export {
  clearLayer,
  cloneLayer,
  colorToStyle,
  copyLayerPixels,
  createLayer,
  getImageData,
  getPixel,
  setPixel,
  type CloneLayerOptions,
} from "@headless-paint/engine";
export {
  calculateRadius,
  drawCircle,
  drawLine,
  drawPath,
  drawVariableWidthPath,
  evaluateParametricCurve,
  interpolateStrokePoints,
} from "@headless-paint/engine";
export {
  renderLayerWithTransform,
  renderLayers,
  type RenderOptions,
} from "@headless-paint/engine";
export {
  compileExpand,
  compileLocalTransforms,
  createDefaultExpandConfig,
  expandPoint,
  expandStroke,
  expandStrokePoints,
  getExpandCount,
} from "@headless-paint/engine";
export {
  appendToCommittedLayer,
  composeLayers,
  renderPendingLayer,
  type ViewTransform as ComposeViewTransform,
} from "@headless-paint/engine";
export {
  createPatternTile,
  DEFAULT_PATTERN_PREVIEW_CONFIG,
  renderPatternPreview,
  type PatternMode,
  type PatternPreviewConfig,
} from "@headless-paint/engine";
export { getContentBounds } from "@headless-paint/engine";
export {
  composeRotation,
  composeScaleAboutAnchor,
  composeTranslation,
  getEdgeMidpoints,
  getOutwardNormal,
  getTransformedCorners,
  isIdentityMatrix,
  isPointInQuad,
  type Mat3Like,
  type QuadCorners,
} from "@headless-paint/engine";
export { transformLayer } from "@headless-paint/engine";
export { wrapShiftLayer } from "@headless-paint/engine";
export {
  mergeLayerDown,
  type MergeLayerDownOptions,
} from "@headless-paint/engine";
export {
  addLayer,
  findLayerById,
  getLayerIndex,
  moveLayer,
  removeLayer,
  updateLayerMeta,
} from "@headless-paint/engine";

export type {
  Point,
  ViewTransform,
  SamplingConfig,
  SamplingState,
  TransformComponents,
  InputPoint,
  FilterType,
  SmoothingConfig,
  StraightLineConfig,
  FilterConfig,
  FilterPipelineConfig,
  CompiledFilterPipeline,
  CausalAdaptiveConfig,
  FilterPipelineState,
  FilterOutput,
  FilterProcessResult,
  FilterPlugin,
  FilterState,
  FilterStepResult,
  GesturePointerEvent,
  GestureConfig,
  GestureState,
  GestureEvent,
} from "@headless-paint/input";

export {
  applyDpr,
  computeSimilarityTransform,
  createViewTransform,
  decomposeTransform,
  fitToView,
  invertViewTransform,
  pan,
  rotate,
  zoom,
} from "@headless-paint/input";
export { screenToLayer, layerToScreen } from "@headless-paint/input";
export { shouldAcceptPoint, createSamplingState } from "@headless-paint/input";
export {
  compileFilterPipeline,
  createFilterPipelineState,
  processPoint,
  finalizePipeline,
  processAllPoints,
} from "@headless-paint/input";
export { getFilterPlugin, registerFilterPlugin } from "@headless-paint/input";
export {
  DEFAULT_GESTURE_CONFIG,
  createGestureState,
  processGestureEvent,
} from "@headless-paint/input";

export type {
  AddLayerCommand,
  AffectedLayers,
  Checkpoint,
  CheckpointPayload,
  ClearCommand,
  Command,
  DuplicateLayerCommand,
  DuplicateLayerOptions,
  DuplicateLayerResult,
  DrawCommand,
  HistoryConfig,
  HistoryMetrics,
  HistoryState,
  LayerDrawCommand,
  MergeLayerDownAtomicOptions,
  MergeLayerDownCommand,
  MergeLayerDownResult,
  PixelScope,
  PushCommandOptions,
  RebuildLayerResult,
  RemoveLayerCommand,
  RenderUpdate,
  ReorderLayerCommand,
  StrokeRuntime,
  StrokeRuntimeDeps,
  StrokeCommand,
  StrokeStartConfig,
  StrokeSessionResult,
  StrokeSessionState,
  TransformMachineEffect,
  TransformMachineEvent,
  StructuralCommand,
  TransformPhase,
  TransformPixelSource,
  TransformTransitionResult,
  TransformLayerCommand,
  WrapShiftCommand,
} from "@headless-paint/stroke";
export {
  DEFAULT_HISTORY_CONFIG,
  isCustomCommand,
  isDrawCommand,
  isLayerDrawCommand,
  isStructuralCommand,
} from "@headless-paint/stroke";
export {
  addPointToSession,
  applyDuplicateLayerCommand,
  applyMergeLayerDownCommand,
  createAddLayerCommand,
  createClearCommand,
  createDuplicateLayerCommand,
  createMergeLayerDownCommand,
  createRemoveLayerCommand,
  createReorderLayerCommand,
  createStrokeCommand,
  createTransformLayerCommand,
  createWrapShiftCommand,
  createInitialTransformPhase,
  duplicateLayerAtomic,
  endStrokeSession,
  mergeLayerDownAtomic,
  startStrokeSession,
  transitionTransform,
} from "@headless-paint/stroke";
export { createStrokeRuntime } from "@headless-paint/stroke";
export {
  canRedo,
  canUndo,
  beginHistoryMutation,
  computeCumulativeOffset,
  createHistoryState,
  findBestCheckpoint,
  findBestCheckpointForLayer,
  getAffectedLayerIds,
  getCommandAt,
  getCommandOffset,
  getCommandPixelScope,
  getCommandsToReplay,
  getCommandsToReplayForLayer,
  getCommandsInRange,
  getHistoryMetrics,
  getLastCommandIndex,
  pushCommand,
  redo,
  undo,
} from "@headless-paint/stroke";
export {
  rebuildLayerFromHistory,
  rebuildLayerState,
  replayCommand,
  replayCommands,
} from "@headless-paint/stroke";
export type {
  CustomCommandExecutor,
  CustomCommandOutcome,
  DirtyHint,
  ExecutorDeps,
  ExecutorFailure,
  ExecutorResult,
  LayerListOp,
  PersistenceEvent,
} from "@headless-paint/stroke";
export {
  executeHistoryOp,
  resolvePushPersistenceEvent,
} from "@headless-paint/stroke";
